version: 2
updates:
- package-ecosystem: gradle
  directories:
  - /
  - /components/abstractions
  - /components/serialization/form
  - /components/serialization/json
  - /components/serialization/text
  - /components/serialization/multipart
  - /components/authentication/azure
  - /components/http/okHttp
  - /components/bundle
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    junit-dependencies:
      patterns:
      - '*junit*'
    open-telemetry:
      patterns:
      - '*opentelemetry*'
  cooldown:
    default-days: 7
- package-ecosystem: gradle
  directories:
  - /components/abstractions/android
  - /components/serialization/form/android
  - /components/serialization/json/android
  - /components/serialization/text/android
  - /components/serialization/multipart/android
  - /components/authentication/azure/android
  - /components/http/okHttp/android
  - /components/bundle/android
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    codeql:
      patterns:
      - 'github/codeql-action*'
    junit-dependencies:
      patterns:
      - '*junit*'
    open-telemetry:
      patterns:
      - '*opentelemetry*'
  cooldown:
    default-days: 7
- package-ecosystem: devcontainers
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
